// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux; // ← maintenant configuré
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZbf19AcQFi7z4LZ7DAI__RxMFMAJkm8',
    appId: '1:846269435063:web:2902967e80b23ff45a5132',
    messagingSenderId: '846269435063',
    projectId: 'up2school-app',
    authDomain: 'up2school-app.firebaseapp.com',
    storageBucket: 'up2school-app.firebasestorage.app',
    measurementId: 'G-7WBHRDNPS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRhXsylT2YdP_80ZTpSHngMW8yhPRcalw',
    appId: '1:846269435063:android:edc094d92f1d7c7e5a5132',
    messagingSenderId: '846269435063',
    projectId: 'up2school-app',
    storageBucket: 'up2school-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClOcTILdEU7Ge9SvlCuUW7qLakrfQEobI',
    appId: '1:846269435063:ios:e3e8cb9c7b67f7fb5a5132',
    messagingSenderId: '846269435063',
    projectId: 'up2school-app',
    storageBucket: 'up2school-app.firebasestorage.app',
    iosBundleId: 'com.up2school',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClOcTILdEU7Ge9SvlCuUW7qLakrfQEobI',
    appId: '1:846269435063:ios:e3e8cb9c7b67f7fb5a5132',
    messagingSenderId: '846269435063',
    projectId: 'up2school-app',
    storageBucket: 'up2school-app.firebasestorage.app',
    iosBundleId: 'com.up2school',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHZbf19AcQFi7z4LZ7DAI__RxMFMAJkm8',
    appId: '1:846269435063:web:2b13b472771264475a5132',
    messagingSenderId: '846269435063',
    projectId: 'up2school-app',
    authDomain: 'up2school-app.firebaseapp.com',
    storageBucket: 'up2school-app.firebasestorage.app',
    measurementId: 'G-EFWLHPLL5G',
  );

  // Configuration Linux (basée sur Android, appId adapté)
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCRhXsylT2YdP_80ZTpSHngMW8yhPRcalw',
    appId: '1:846269435063:linux:edc094d92f1d7c7e5a5132', // suffixe "linux"
    messagingSenderId: '846269435063',
    projectId: 'up2school-app',
    storageBucket: 'up2school-app.firebasestorage.app',
  );
}
