name: Build Windows Flutter App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Show Flutter version
        run: flutter --version

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Generate App Icons
        run: dart run flutter_launcher_icons

      - name: Build Windows Installer
        run: dart run inno_bundle:build

      - name: Rename Installer
        run: Rename-Item -Path "build\windows\x64\installer\Release\*.exe" -NewName "UY1-Lib.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: frontend/build/windows/x64/installer/Release/
